Developer guide
AY2223S1-CS2103T-W17-3/tp pull request #246
Opened 2022-11-04 18:24 UTC by lilythchu

2022-11-06 14:33 UTC, heyzec commented
![image](https://user-images.githubusercontent.com/61238538/200176841-900f3b2c-645e-46fa-96a2-d3fe5aa42d8c.png)

I think this is List<Tag> (?)

2022-11-06 18:40 UTC, LimAiLin requested changes

2022-11-06 18:40 UTC, LimAiLin commented on docs/DeveloperGuide.md
> +* stores the address book data i.e., all `Student` objects (which are contained in a `UniqueStudentList` object), `Tutorial`, `Consultation`, `Reminder` objects
address book should be changed to ModQuik data

2022-11-07 07:49 UTC, april-anh approved these changes

2022-11-07 10:13 UTC, LimAiLin approved these changes

2022-11-07 10:13 UTC, merged