Updated student data
AY2223S1-CS2103T-W17-3/tp pull request #60
Opened 2022-10-13 21:36 UTC by LimAiLin

2022-10-14 00:34 UTC, yeoyujie requested changes
Fix the checkestyle errors

2022-10-14 00:34 UTC, yeoyujie commented on src/main/java/seedu/address/model/student/Phone.java
>      public static final String VALIDATION_REGEX = "\\d{3,}";
Consider changing to 8 digits long

2022-10-14 00:52 UTC, yeoyujie commented on src/main/java/seedu/address/logic/parser/CliSyntax.java
>      public static final Prefix PREFIX_TIMESLOT = new Prefix("t/");
Lets change timeslot to some other alternatives as a temporary solution so that its diff from tags

2022-10-14 00:54 UTC, yeoyujie reviewed
We should standardise Cli syntax prefix as tags and timeslot both currently uses /t

2022-10-14 00:54 UTC, yeoyujie commented on src/main/java/seedu/address/logic/parser/CliSyntax.java
>      public static final Prefix PREFIX_TIMESLOT = new Prefix("t/");
Let's change timeslot to some other alternatives as a temporary solution so that its diff from the tags

2022-10-15 12:10 UTC, lilythchu approved these changes

2022-10-17 06:20 UTC, yeoyujie approved these changes
LGTM

2022-10-17 06:20 UTC, merged